### ISSUE TITLE
Improve support for right-to-left languages

### ISSUE THREAD

**Issue by fabiocolacio** [Mandarancio/scidown#1]
steps can be taken to improve support for right-to-left languages.

As suggested by @ronhasson, adding the attribute ``dir="auto"`` to lists can improve the look of right-to-left text in lists.

**Comment by ronhasson** [comment]
As mentioned in  [fabiocolacio/Marker pull#182](https://github.com/fabiocolacio/Marker/pull/182)

I think the line we need to change is: https://github.com/Mandarancio/scidown/blob/be4b5db8c6dfd5d3e15533e3155b4778428f6341/src/html.c#L343
but you probably know the code better than me.

**Comment by Mandarancio** [comment]
the `dir="auto"` attribute has to be added to all tags, only to list or on the `<html>` tag as shown [here](https://www.w3.org/International/questions/qa-html-dir)?

**Comment by ronhasson** [comment]
only to the list is enough.
it will make it so each list will change direction based on the first item's lang direction 

adding this to the html will make all the page either LTR or RTL ( you won't be able to combine both ).
and I don't think adding this to all the tags will be necessary (maybe some of them wont accept the attribute?).

**Comment by Mandarancio** [comment]
I pushed the changes, I added the `dir` only to the lists (both `ul` and `ol`). I also pushed the changes in marker, please test it and let me know if does work :)

**Comment by ronhasson** [comment]
The lists look perfect.

@\toc unfortunately, doesn't

![screenshot from 2018-04-07 13-06-52](https://user-images.githubusercontent.com/7431072/38453851-0b8a59c8-3a65-11e8-8ca8-24486bc809c9.png)

Since 1 and 1.1 are RTL the list should too.
It seems the ul doesnt conatin the `dir="auto"`

**Comment by ronhasson** [comment]
Tables have the same problem and more, when you type in Hebrew the function generates the table correctly but when the html engine shows it, the columns are in reverse order(from right to left).

The solution is also to attach `dir="auto"` to the `<table>` elements too.

The second problem with tables is they are always sticking to the left side of the page,
I know you can change the text alignment with the |:----:| but I have no Idea how to make them stick to the right when needed.

**Comment by Mandarancio** [comment]
Ok I will add the `dir="auto"` to the `toc` (that is generated independently from the normal list, and that's why it doesn't have it) and to the `table` :)

**Comment by Mandarancio** [comment]
I added the the `dir="auto"` tag to toc and table elements and updated `marker` with it. @ronhasson Let me know if everything is fine now

**Comment by ronhasson** [comment]
I really don't want to bother you, (and sorry I disappeared )
I can't see the `dir="auto"` in the ul of the `@tos` .

I could swear it worked before. maybe it was when I installed it manually in the past or maybe I'm imagining it and its just because I haven't used `@tos` in a long time.
